### ISSUE TITLE
Dismiss Semantic UI for vuejs.

### ISSUE THREAD

**Issue by haldrix** [academia-de-codigo/noire-server#9]
Thanks guys, this project is a real good piece of work for studying. I love it. 
Is it possible to explain how one can separate SUI from your project and replace it with something else like vuejs front. I'll love to connect any vuejs framework or config framework like nuxtjs but don't know where to start ? I know that issues are not the right place to ask these kind of questions but I try my luck 😉

**Comment by ferrao** [comment]
Thank you @haldrix, I do intend to remove all server side rendering from the project eventually, as we are not using it on any of our projects (all our front-ends are currently rendered client side using React).

Until we do so, all you have to do is disable both `web` and `webTls` connections on `lib/config.js` and you are ready to go!
